# Generated by Django 4.0.3 on 2022-04-04 18:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_chat_professor_research_room_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='institute_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_institute',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
