# Generated by Django 4.0.3 on 2022-04-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_professor_active_internships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='prof_name',
        ),
        migrations.AddField(
            model_name='internship',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.professor'),
        ),
    ]
